
modLoader = "javafml" 
loaderVersion = "${loader_version_range}" 
license = "${mod_license}"
issueTrackerURL="https://github.com/thebungler/sloppyspoof/issues"
[[mods]] 
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/thebungler/sloppyspoof"
#logoFile="sloppyspoof.png"
#credits="Lorem ipsum" 
authors = "${mod_authors}"
# IGNORE_ALL_VERSION means that your mod will not cause a red X if it's present on the client or the server
displayTest="IGNORE_ALL_VERSION" 
description = '''${mod_description}'''
[[dependencies."${mod_id}"]] 
modId = "forge" 
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "CLIENT"
[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
